export const defaultTexts = {
  appTitle: "UpProfessional",
  becomeProfessional: "Soy profesional",
  findProfessional: "Buscar profesional",
  requestQuote: "Solicitar presupuesto",
  howItWorks: "Como funciona",
  faq: "FAQ",
  loading: "Cargando...",
  signIn: "Iniciar sesión",
  signInDescription: "Ingresa tu email y contraseña para iniciar sesión",
  signInWithGoogle: "Iniciar sesión con Google",
  emailPlaceholder: "Ingrese tu email",
  passwordPlaceholder: "Ingrese su contraseña",
  rememberMe: "Mantener sesión activa",
  forgotPassword: "¿Olvidaste tu contraseña?",
  noAccount: "¿No tienes una cuenta?",
  signUp: "Regístrate",
  backToDashboard: "Volver al Inicio",
  signUpDescription: "Crea tu cuenta para comenzar",
  namePlaceholder: "Ingrese su nombre",
  lastNamePlaceholder: "Ingrese su apellido",
  or: "o",
  name: "Nombre",
  lastName: "Apellido",
  email: "Email",
  phone: "Teléfono",
  password: "Contraseña",
  confirmPassword: "Confirmar contraseña",
  signUpWithGoogle: "Registrate con Google",
  alreadyHaveAccount: "¿Ya tienes una cuenta?",
  confirmPasswordPlaceholder: "Confirma tu contraseña",
  selectOption: "Selecciona una opción",
  client: "Cliente",
  professional: "Profesional",
  admin: "Administrador",
  whoYouAre: "¿Que tipo de usuario eres?",
  serviceType: "Tipo de servicio",
  zone: "Zona",
  selectLocation: "Zona/Localidad",
  service: "Servicio",
  reviews: "Reseñas",
  noFoundProfessional: "No se encontraron el profesional",
  personalInfo: "Información personal",
} as const;

export type TextKey = keyof typeof defaultTexts;

export function getText(key: TextKey): string {
  return defaultTexts[key] ?? key;
}
